service: sltbonline-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_URI: ${env:MONGO_URI} # AWS Lambda Environment Variable for MongoDB URI

functions:
  dashboard:
    handler: handler.dashboard  # Referencing handler.js to invoke the dashboard function
    events:
      - http:
          path: dashboard
          method: get
          cors: true  # Allow CORS for this endpoint

  # Add other functions if needed (e.g., auth, buses, routes)
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: post
          cors: true

  bus:
    handler: handler.bus
    events:
      - http:
          path: buses
          method: get
          cors: true

  route:
    handler: handler.route
    events:
      - http:
          path: routes
          method: get
          cors: true

resources:
  resources:
    # Add any additional AWS resources here if required (e.g., DynamoDB, S3)
    # Example:
    # myDynamoDbTable:
    #   Type: 'AWS::DynamoDB::Table'
    #   Properties:
    #     TableName: 'my-table'
    #     AttributeDefinitions:
    #       - AttributeName: 'id'
    #         AttributeType: 'S'
    #     KeySchema:
    #       - AttributeName: 'id'
    #         KeyType: 'HASH'
    #     ProvisionedThroughput:
    #       ReadCapacityUnits: 5
    #       WriteCapacityUnits: 5
